### ISSUE TITLE
Can you give please dataset on the csv file)

### ISSUE THREAD

**Issue by Guzel2001** [dashaub/kohonen4j#6]

**Comment by dashaub** [comment]
Any csv with only numeric values should do. The first row is treated as a header and ignored. I used the "wines" dataset described [here](https://artax.karlin.mff.cuni.cz/r-help/library/pdfCluster/html/wine.html). The link there appears broken, so I've uploaded it (renamed it to .txt since Github doesn't like .csv)
[wines.txt](https://github.com/dashaub/kohonen4j/files/883596/wines.txt)
